sudo: required
before_install:
  - sudo apt-get install libice-dev
  - sudo apt-get install libice
  - sudo apt-get install freeglut3-dev
  - sudo apt-get install cmake

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

install:

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
